// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3d252059-96c5-4c80-9d72-1aa4061390fa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_HgIh0SnD6",
    "aws_user_pools_web_client_id": "5tj103gll4c5bvfv405bb7g74c"
};


export default awsmobile;
